**NumPY** by aomine

**Arrays**

In [25]:
import numpy as np
my_list =[1,2,3]
print(type(np.array(my_list)))
print(my_list)

<class 'numpy.ndarray'>
[1, 2, 3]


In [26]:
import numpy as np
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix_numpy = np.array(my_matrix)
print(my_matrix_numpy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
array = np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [28]:
array_even = np.arange(0,10,2)
print(array_even)

[0 2 4 6 8]


In [32]:
array_zeros = np.zeros(3)
print(array_zeros)

[0. 0. 0.]


In [34]:
matrix_zeros = np.zeros((5,5))
print(matrix_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
array_one = np.ones((6))
print(array_one)

[1. 1. 1. 1. 1. 1.]


In [38]:
matrix_one = np.ones((6,6))
print(matrix_one)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [39]:
equidistance  = np.linspace(0,10,5)
print(equidistance)

[ 0.   2.5  5.   7.5 10. ]


In [41]:
equidistance_0 = np.linspace(0,10,100)
print(equidistance_0)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [46]:
matrix_1 = np.eye(15)
print(matrix_1)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [47]:
random_0_1 = np.random.rand(2)
print(random_0_1)

[0.09524031 0.89868179]


In [49]:
random_0_1_matrix = np.random.rand(5,5)
print(random_0_1_matrix)

[[0.4983195  0.36944335 0.39497162 0.06212906 0.23840968]
 [0.85339357 0.17611731 0.07014393 0.07968493 0.97602773]
 [0.5161866  0.48089127 0.31508996 0.95399451 0.23890343]
 [0.06609714 0.06121427 0.52310355 0.7855004  0.59581748]
 [0.87558227 0.50947613 0.14094152 0.08645981 0.22944417]]


In [51]:
random_all = np.random.randint(0,100,5)
print(random_all)

[22 77 77 74 47]


In [52]:
np.random.seed(14)
random_all_seed = np.random.randint(0,100,5)
print(random_all_seed)


[88 12 22 71 28]


In [53]:
np.random.seed(14)
random_all_seed = np.random.randint(0,100,5)
print(random_all_seed)


[88 12 22 71 28]


In [55]:
arr = np.arange(0,100)
arr.reshape(10,10)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [67]:
arr_for = np.arange(0,100)
ranarr = np.random.randint(0,100,10)
print(ranarr.min())
print(ranarr.max())
print(ranarr.argmin())


12
99
5


In [68]:
print(arr_for.dtype)

int64
