**Operation**

In [ ]:
import numpy as np
arr = np.arange(0,20,2)
print(arr)
print(arr + arr)
print(arr * arr)
print(arr - arr)


[ 0  2  4  6  8 10 12 14 16 18]
[ 0  4  8 12 16 20 24 28 32 36]
[  0   4  16  36  64 100 144 196 256 324]
[0 0 0 0 0 0 0 0 0 0]


In [37]:
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))

[0.         1.41421356 2.         2.44948974 2.82842712 3.16227766
 3.46410162 3.74165739 4.         4.24264069]
[1.00000000e+00 7.38905610e+00 5.45981500e+01 4.03428793e+02
 2.98095799e+03 2.20264658e+04 1.62754791e+05 1.20260428e+06
 8.88611052e+06 6.56599691e+07]
[ 0.          0.90929743 -0.7568025  -0.2794155   0.98935825 -0.54402111
 -0.53657292  0.99060736 -0.28790332 -0.75098725]


In [38]:
print(arr.sum())
print(arr.mean())
print(arr.max())

90
9.0
18


In [50]:
arrr = np.arange(0,100,2)
print(arrr.reshape(10,5))
print(arrr.sum())
print(arrr.sum(axis=0))

[[ 0  2  4  6  8]
 [10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]
 [70 72 74 76 78]
 [80 82 84 86 88]
 [90 92 94 96 98]]
2450
2450
